name: BetterWhitelist
api-version: 1.13
authors:
  - cocahonka
  - vmlakk
  - Forked by DeinAlbtraumTV
main: com.cocahonka.comfywhitelist.ComfyWhitelist
version: @version@
softdepend: ["kotlin-stdlib"]
commands:
  betterwhitelist:
    description: BetterWhitelist management.
    aliases: [ wl ]
    permission: betterwhitelist.betterwhitelist
permissions:
  betterwhitelist.*:
    description: Give access to all BetterWhitelist commands.
    default: op
    children:
      betterwhitelist.add: true
      betterwhitelist.remove: true
      betterwhitelist.clear: true
      betterwhitelist.list: true
      betterwhitelist.on: true
      betterwhitelist.off: true
      betterwhitelist.reload: true
      betterwhitelist.help: true
  betterwhitelist.betterwhitelist:
    description: Give access to main BetterWhitelist command.
    default: op
  betterwhitelist.add:
    description: Give access to add player name to BetterWhitelist.
    default: op
  betterwhitelist.remove:
    description: Give access to remove player name from BetterWhitelist.
    default: op
    children:
      betterwhitelist.clear: true
  betterwhitelist.clear:
    description: Give access to hard-reset BetterWhitelist.
    default: false
  betterwhitelist.list:
    description: Give access to display all player names in BetterWhitelist.
    default: op
  betterwhitelist.on:
    description: Give access to enable BetterWhitelist.
    default: op
  betterwhitelist.off:
    description: Give access to disable BetterWhitelist.
    default: op
  betterwhitelist.reload:
    description: Give access to reload BetterWhitelist.
    default: op
  betterwhitelist.help:
    description: Displays information about BetterWhitelist commands
    default: op
  betterwhitelist.status:
    description: Displays status of the BetterWhitelist (on/off)
    default: op